version: '3'
services:
  mosquitto:
    image: europe-west1-docker.pkg.dev/bringauto-infrastructure/virtual-platform/bringauto-mosquitto:latest
    profiles: ["all", "without-industrial-portal", "without-autonomy"]
    networks:
      vpcbr:
        ipv4_address: 10.5.0.2
    ports:
      - 8086:8086
      - 1883:1883
      - 9003:9003
    restart: on-failure:10
    
  virtual-industrial-portal:
    image: europe-west1-docker.pkg.dev/bringauto-infrastructure/virtual-platform/virtual-industrial-portal:latest
    profiles: ["all", "without-autonomy"]
    volumes: 
      - ./docker_volumes/virtual-industrial-portal:/virtual-industrial-portal/log
    networks:
      vpcbr:
        ipv4_address: 10.5.0.3
    entrypoint: ["/virtual-industrial-portal/virtual-industrial-portal-app",
                "--broker-ip=10.5.0.2",
                "--broker-port=1883",
                "--log-path=/virtual-industrial-portal/log/"]
    restart: on-failure:10

  bringauto-daemon:
    image: europe-west1-docker.pkg.dev/bringauto-infrastructure/virtual-platform/bringauto-daemon:latest
    profiles: ["all", "without-industrial-portal", "without-autonomy"]
    volumes: 
      - ./docker_volumes/bringauto-daemon:/bringauto-daemon/log
    networks:
      vpcbr:
        ipv4_address: 10.5.0.4
    ports:
      - 1536:1536
    entrypoint: ["/bringauto-daemon/_build/components/industrial_portal/industrial_portal",
                "--mode=mqtt",
                "--company=roboauto",
                "--place=kralovopolska",
                "--vehicle-name=car1",
                "--broker-ip=10.5.0.2",
                "--broker-port=1883",
                "--port=1536",
                "--log-path=/bringauto-daemon/log/"]
    restart: on-failure:10

  virtual-vehicle-utility:
    image: europe-west1-docker.pkg.dev/bringauto-infrastructure/virtual-platform/virtual-vehicle-utility:latest
    profiles: ["all", "without-industrial-portal"]
    volumes: 
      - ./docker_volumes/virtual-vehicle-utility:/virtual-vehicle-utility/log
    networks:
      vpcbr:
        ipv4_address: 10.5.0.5
    entrypoint: ["/virtual-vehicle-utility/VirtualVehicle", 
                "--map=/virtual-vehicle-utility/maps/BorsodChem.osm",
                "--verbose", 
                "--route=borsodchem",
                "--ip=10.5.0.4",
                "--port=1536", 
                "--wait=10",
                "--log-path=/virtual-vehicle-utility/log/"]
    depends_on: 
        - bringauto-daemon
    restart: on-failure:10

networks:
  vpcbr:
    driver: bridge
    ipam:
     config:
       - subnet: 10.5.0.0/24
         gateway: 10.5.0.1

