//*
// Detailed description can be found at Car State Prorocol
// document located at our Google Disk
// https://drive.google.com/drive/folders/1ZE9VRs86QtP6GqTJBl6vRJLmkh1lTEc5
//

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.20.2
// source: CarStateProtocol.proto

package ba_proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

//*
// State of the car according to The Autonomy system.
// Change of the State is only possible as described - no side effects allowed!
type CarStatus_State int32

const (
	//*
	// Car is in IDLE mode. Waiting for CarCommand message receive.
	// This state assume that the CarStatus::telemetry::speed is zero!
	CarStatus_IDLE CarStatus_State = 0
	//*
	// Car is driving (to the target stop).
	CarStatus_DRIVE CarStatus_State = 1
	//*
	// Car is in the specified stop. It does not imply that the car is IDLE.
	// This state assume that the CarStatus::telemetry::speed is zero!
	CarStatus_IN_STOP CarStatus_State = 2
	//*
	// There is an Obstacle which will cause collision if not removed.
	// The transition from this state to another is defined by The Autonomy implementation.
	CarStatus_OBSTACLE CarStatus_State = 3
	//*
	// Car is in an error state.
	// State reflects that the car is in critical condition and needs an assistance.
	// The transition from this state to another is defined by The Autonomy implementation.
	CarStatus_ERROR CarStatus_State = 4
)

// Enum value maps for CarStatus_State.
var (
	CarStatus_State_name = map[int32]string{
		0: "IDLE",
		1: "DRIVE",
		2: "IN_STOP",
		3: "OBSTACLE",
		4: "ERROR",
	}
	CarStatus_State_value = map[string]int32{
		"IDLE":     0,
		"DRIVE":    1,
		"IN_STOP":  2,
		"OBSTACLE": 3,
		"ERROR":    4,
	}
)

func (x CarStatus_State) Enum() *CarStatus_State {
	p := new(CarStatus_State)
	*p = x
	return p
}

func (x CarStatus_State) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CarStatus_State) Descriptor() protoreflect.EnumDescriptor {
	return file_CarStateProtocol_proto_enumTypes[0].Descriptor()
}

func (CarStatus_State) Type() protoreflect.EnumType {
	return &file_CarStateProtocol_proto_enumTypes[0]
}

func (x CarStatus_State) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CarStatus_State.Descriptor instead.
func (CarStatus_State) EnumDescriptor() ([]byte, []int) {
	return file_CarStateProtocol_proto_rawDescGZIP(), []int{0, 0}
}

//*
// Action which car must take.
// Received action has an immediate effect to the state of the car (CarStatus::state)
// @see CarStatus::State
type CarCommand_Action int32

const (
	//*
	// No action performed. Used as a default value.
	// Does not interact with CarCommand::stops logic.
	CarCommand_NO_ACTION CarCommand_Action = 0
	//*
	// Stop The car!
	// Independent on content of CarCommands::stops
	CarCommand_STOP CarCommand_Action = 1
	//*
	// Start the car!
	// If there are stops in CarCommands::stops the car shall start driving to the next stop.
	CarCommand_START CarCommand_Action = 2
)

// Enum value maps for CarCommand_Action.
var (
	CarCommand_Action_name = map[int32]string{
		0: "NO_ACTION",
		1: "STOP",
		2: "START",
	}
	CarCommand_Action_value = map[string]int32{
		"NO_ACTION": 0,
		"STOP":      1,
		"START":     2,
	}
)

func (x CarCommand_Action) Enum() *CarCommand_Action {
	p := new(CarCommand_Action)
	*p = x
	return p
}

func (x CarCommand_Action) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CarCommand_Action) Descriptor() protoreflect.EnumDescriptor {
	return file_CarStateProtocol_proto_enumTypes[1].Descriptor()
}

func (CarCommand_Action) Type() protoreflect.EnumType {
	return &file_CarStateProtocol_proto_enumTypes[1]
}

func (x CarCommand_Action) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CarCommand_Action.Descriptor instead.
func (CarCommand_Action) EnumDescriptor() ([]byte, []int) {
	return file_CarStateProtocol_proto_rawDescGZIP(), []int{1, 0}
}

//*
// Car status information.
// From Client to Server only
type CarStatus struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	//*
	// Telemetry
	Telemetry *CarStatus_Telemetry `protobuf:"bytes,1,opt,name=telemetry,proto3" json:"telemetry,omitempty"`
	//*
	// State of the Car.
	// If not set Car is in the IDLE state!
	// OPTIONAL
	State CarStatus_State `protobuf:"varint,2,opt,name=state,proto3,enum=CarStateProtocol.CarStatus_State" json:"state,omitempty"`
	//*
	// Name of the stop as specified in CarCommand::stops.
	// OPTIONAL
	Stop *Stop `protobuf:"bytes,3,opt,name=stop,proto3" json:"stop,omitempty"`
}

func (x *CarStatus) Reset() {
	*x = CarStatus{}
	if protoimpl.UnsafeEnabled {
		mi := &file_CarStateProtocol_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CarStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CarStatus) ProtoMessage() {}

func (x *CarStatus) ProtoReflect() protoreflect.Message {
	mi := &file_CarStateProtocol_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CarStatus.ProtoReflect.Descriptor instead.
func (*CarStatus) Descriptor() ([]byte, []int) {
	return file_CarStateProtocol_proto_rawDescGZIP(), []int{0}
}

func (x *CarStatus) GetTelemetry() *CarStatus_Telemetry {
	if x != nil {
		return x.Telemetry
	}
	return nil
}

func (x *CarStatus) GetState() CarStatus_State {
	if x != nil {
		return x.State
	}
	return CarStatus_IDLE
}

func (x *CarStatus) GetStop() *Stop {
	if x != nil {
		return x.Stop
	}
	return nil
}

//*
// Car commands received from BringAuto cloud
// From BAD to Client only.
type CarCommand struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	//*
	// List of stops where the car shall go. Car goes from one stop to another by the order specified by the list.
	// OPTIONAL
	Stops         []*Stop           `protobuf:"bytes,1,rep,name=stops,proto3" json:"stops,omitempty"`
	Action        CarCommand_Action `protobuf:"varint,2,opt,name=action,proto3,enum=CarStateProtocol.CarCommand_Action" json:"action,omitempty"`
	Route         string            `protobuf:"bytes,3,opt,name=route,proto3" json:"route,omitempty"`
	RouteStations []*Station        `protobuf:"bytes,4,rep,name=routeStations,proto3" json:"routeStations,omitempty"`
}

func (x *CarCommand) Reset() {
	*x = CarCommand{}
	if protoimpl.UnsafeEnabled {
		mi := &file_CarStateProtocol_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CarCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CarCommand) ProtoMessage() {}

func (x *CarCommand) ProtoReflect() protoreflect.Message {
	mi := &file_CarStateProtocol_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CarCommand.ProtoReflect.Descriptor instead.
func (*CarCommand) Descriptor() ([]byte, []int) {
	return file_CarStateProtocol_proto_rawDescGZIP(), []int{1}
}

func (x *CarCommand) GetStops() []*Stop {
	if x != nil {
		return x.Stops
	}
	return nil
}

func (x *CarCommand) GetAction() CarCommand_Action {
	if x != nil {
		return x.Action
	}
	return CarCommand_NO_ACTION
}

func (x *CarCommand) GetRoute() string {
	if x != nil {
		return x.Route
	}
	return ""
}

func (x *CarCommand) GetRouteStations() []*Station {
	if x != nil {
		return x.RouteStations
	}
	return nil
}

//*
// Mission for the car.
type Stop struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	//*
	// The name of the stop where to go.
	To string `protobuf:"bytes,1,opt,name=to,proto3" json:"to,omitempty"`
}

func (x *Stop) Reset() {
	*x = Stop{}
	if protoimpl.UnsafeEnabled {
		mi := &file_CarStateProtocol_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Stop) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Stop) ProtoMessage() {}

func (x *Stop) ProtoReflect() protoreflect.Message {
	mi := &file_CarStateProtocol_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Stop.ProtoReflect.Descriptor instead.
func (*Stop) Descriptor() ([]byte, []int) {
	return file_CarStateProtocol_proto_rawDescGZIP(), []int{2}
}

func (x *Stop) GetTo() string {
	if x != nil {
		return x.To
	}
	return ""
}

//*
// Station on the route.
type Station struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	//*
	// The name of the station.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	//*
	// The position of the station.
	Position *Station_Position `protobuf:"bytes,2,opt,name=position,proto3" json:"position,omitempty"`
}

func (x *Station) Reset() {
	*x = Station{}
	if protoimpl.UnsafeEnabled {
		mi := &file_CarStateProtocol_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Station) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Station) ProtoMessage() {}

func (x *Station) ProtoReflect() protoreflect.Message {
	mi := &file_CarStateProtocol_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Station.ProtoReflect.Descriptor instead.
func (*Station) Descriptor() ([]byte, []int) {
	return file_CarStateProtocol_proto_rawDescGZIP(), []int{3}
}

func (x *Station) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Station) GetPosition() *Station_Position {
	if x != nil {
		return x.Position
	}
	return nil
}

type CarStatus_Telemetry struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	//*
	// vehicle speed in [m/s]
	// - positive value implies Forward car moving,
	// - negative value implies Backward car moving,
	// - zero value implies that the car stays at a place.
	Speed float64 `protobuf:"fixed64,1,opt,name=speed,proto3" json:"speed,omitempty"`
	//*
	// Fuel of the car in percents.
	// - 0.0 means empty battery or tank,
	// - 1.0 means full battery or tank.
	// Interpolation between 0.0 and 1.0 must be linear!
	Fuel float64 `protobuf:"fixed64,2,opt,name=fuel,proto3" json:"fuel,omitempty"`
	//*
	// Car position in the global map (WGS84)
	Position *CarStatus_Position `protobuf:"bytes,3,opt,name=position,proto3" json:"position,omitempty"`
}

func (x *CarStatus_Telemetry) Reset() {
	*x = CarStatus_Telemetry{}
	if protoimpl.UnsafeEnabled {
		mi := &file_CarStateProtocol_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CarStatus_Telemetry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CarStatus_Telemetry) ProtoMessage() {}

func (x *CarStatus_Telemetry) ProtoReflect() protoreflect.Message {
	mi := &file_CarStateProtocol_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CarStatus_Telemetry.ProtoReflect.Descriptor instead.
func (*CarStatus_Telemetry) Descriptor() ([]byte, []int) {
	return file_CarStateProtocol_proto_rawDescGZIP(), []int{0, 0}
}

func (x *CarStatus_Telemetry) GetSpeed() float64 {
	if x != nil {
		return x.Speed
	}
	return 0
}

func (x *CarStatus_Telemetry) GetFuel() float64 {
	if x != nil {
		return x.Fuel
	}
	return 0
}

func (x *CarStatus_Telemetry) GetPosition() *CarStatus_Position {
	if x != nil {
		return x.Position
	}
	return nil
}

// GPS position of the car
type CarStatus_Position struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	//*
	// WGS84 latitude,
	Latitude float64 `protobuf:"fixed64,1,opt,name=latitude,proto3" json:"latitude,omitempty"`
	//*
	// WGS84 longitude
	Longitude float64 `protobuf:"fixed64,2,opt,name=longitude,proto3" json:"longitude,omitempty"`
	//*
	// altitude in [m]
	Altitude float64 `protobuf:"fixed64,3,opt,name=altitude,proto3" json:"altitude,omitempty"`
}

func (x *CarStatus_Position) Reset() {
	*x = CarStatus_Position{}
	if protoimpl.UnsafeEnabled {
		mi := &file_CarStateProtocol_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CarStatus_Position) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CarStatus_Position) ProtoMessage() {}

func (x *CarStatus_Position) ProtoReflect() protoreflect.Message {
	mi := &file_CarStateProtocol_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CarStatus_Position.ProtoReflect.Descriptor instead.
func (*CarStatus_Position) Descriptor() ([]byte, []int) {
	return file_CarStateProtocol_proto_rawDescGZIP(), []int{0, 1}
}

func (x *CarStatus_Position) GetLatitude() float64 {
	if x != nil {
		return x.Latitude
	}
	return 0
}

func (x *CarStatus_Position) GetLongitude() float64 {
	if x != nil {
		return x.Longitude
	}
	return 0
}

func (x *CarStatus_Position) GetAltitude() float64 {
	if x != nil {
		return x.Altitude
	}
	return 0
}

// GPS position added in v1.2, must be on both places (here and Status) because of backwards compability
type Station_Position struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	//*
	// WGS84 latitude,
	Latitude float64 `protobuf:"fixed64,1,opt,name=latitude,proto3" json:"latitude,omitempty"`
	//*
	// WGS84 longitude
	Longitude float64 `protobuf:"fixed64,2,opt,name=longitude,proto3" json:"longitude,omitempty"`
	//*
	// altitude in [m]
	Altitude float64 `protobuf:"fixed64,3,opt,name=altitude,proto3" json:"altitude,omitempty"`
}

func (x *Station_Position) Reset() {
	*x = Station_Position{}
	if protoimpl.UnsafeEnabled {
		mi := &file_CarStateProtocol_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Station_Position) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Station_Position) ProtoMessage() {}

func (x *Station_Position) ProtoReflect() protoreflect.Message {
	mi := &file_CarStateProtocol_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Station_Position.ProtoReflect.Descriptor instead.
func (*Station_Position) Descriptor() ([]byte, []int) {
	return file_CarStateProtocol_proto_rawDescGZIP(), []int{3, 0}
}

func (x *Station_Position) GetLatitude() float64 {
	if x != nil {
		return x.Latitude
	}
	return 0
}

func (x *Station_Position) GetLongitude() float64 {
	if x != nil {
		return x.Longitude
	}
	return 0
}

func (x *Station_Position) GetAltitude() float64 {
	if x != nil {
		return x.Altitude
	}
	return 0
}

var File_CarStateProtocol_proto protoreflect.FileDescriptor

var file_CarStateProtocol_proto_rawDesc = []byte{
	0x0a, 0x16, 0x43, 0x61, 0x72, 0x53, 0x74, 0x61, 0x74, 0x65, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x63,
	0x6f, 0x6c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x10, 0x43, 0x61, 0x72, 0x53, 0x74, 0x61,
	0x74, 0x65, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x22, 0xd4, 0x03, 0x0a, 0x09, 0x43,
	0x61, 0x72, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x43, 0x0a, 0x09, 0x74, 0x65, 0x6c, 0x65,
	0x6d, 0x65, 0x74, 0x72, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x25, 0x2e, 0x43, 0x61,
	0x72, 0x53, 0x74, 0x61, 0x74, 0x65, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2e, 0x43,
	0x61, 0x72, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x2e, 0x54, 0x65, 0x6c, 0x65, 0x6d, 0x65, 0x74,
	0x72, 0x79, 0x52, 0x09, 0x74, 0x65, 0x6c, 0x65, 0x6d, 0x65, 0x74, 0x72, 0x79, 0x12, 0x37, 0x0a,
	0x05, 0x73, 0x74, 0x61, 0x74, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x21, 0x2e, 0x43,
	0x61, 0x72, 0x53, 0x74, 0x61, 0x74, 0x65, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2e,
	0x43, 0x61, 0x72, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x65, 0x52,
	0x05, 0x73, 0x74, 0x61, 0x74, 0x65, 0x12, 0x2a, 0x0a, 0x04, 0x73, 0x74, 0x6f, 0x70, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x43, 0x61, 0x72, 0x53, 0x74, 0x61, 0x74, 0x65, 0x50,
	0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2e, 0x53, 0x74, 0x6f, 0x70, 0x52, 0x04, 0x73, 0x74,
	0x6f, 0x70, 0x1a, 0x77, 0x0a, 0x09, 0x54, 0x65, 0x6c, 0x65, 0x6d, 0x65, 0x74, 0x72, 0x79, 0x12,
	0x14, 0x0a, 0x05, 0x73, 0x70, 0x65, 0x65, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x01, 0x52, 0x05,
	0x73, 0x70, 0x65, 0x65, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x66, 0x75, 0x65, 0x6c, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x01, 0x52, 0x04, 0x66, 0x75, 0x65, 0x6c, 0x12, 0x40, 0x0a, 0x08, 0x70, 0x6f, 0x73,
	0x69, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x24, 0x2e, 0x43, 0x61,
	0x72, 0x53, 0x74, 0x61, 0x74, 0x65, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2e, 0x43,
	0x61, 0x72, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x2e, 0x50, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f,
	0x6e, 0x52, 0x08, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x1a, 0x60, 0x0a, 0x08, 0x50,
	0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x1a, 0x0a, 0x08, 0x6c, 0x61, 0x74, 0x69, 0x74,
	0x75, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x01, 0x52, 0x08, 0x6c, 0x61, 0x74, 0x69, 0x74,
	0x75, 0x64, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x6c, 0x6f, 0x6e, 0x67, 0x69, 0x74, 0x75, 0x64, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x01, 0x52, 0x09, 0x6c, 0x6f, 0x6e, 0x67, 0x69, 0x74, 0x75, 0x64,
	0x65, 0x12, 0x1a, 0x0a, 0x08, 0x61, 0x6c, 0x74, 0x69, 0x74, 0x75, 0x64, 0x65, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x01, 0x52, 0x08, 0x61, 0x6c, 0x74, 0x69, 0x74, 0x75, 0x64, 0x65, 0x22, 0x42, 0x0a,
	0x05, 0x53, 0x74, 0x61, 0x74, 0x65, 0x12, 0x08, 0x0a, 0x04, 0x49, 0x44, 0x4c, 0x45, 0x10, 0x00,
	0x12, 0x09, 0x0a, 0x05, 0x44, 0x52, 0x49, 0x56, 0x45, 0x10, 0x01, 0x12, 0x0b, 0x0a, 0x07, 0x49,
	0x4e, 0x5f, 0x53, 0x54, 0x4f, 0x50, 0x10, 0x02, 0x12, 0x0c, 0x0a, 0x08, 0x4f, 0x42, 0x53, 0x54,
	0x41, 0x43, 0x4c, 0x45, 0x10, 0x03, 0x12, 0x09, 0x0a, 0x05, 0x45, 0x52, 0x52, 0x4f, 0x52, 0x10,
	0x04, 0x22, 0xfc, 0x01, 0x0a, 0x0a, 0x43, 0x61, 0x72, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64,
	0x12, 0x2c, 0x0a, 0x05, 0x73, 0x74, 0x6f, 0x70, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x16, 0x2e, 0x43, 0x61, 0x72, 0x53, 0x74, 0x61, 0x74, 0x65, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x63,
	0x6f, 0x6c, 0x2e, 0x53, 0x74, 0x6f, 0x70, 0x52, 0x05, 0x73, 0x74, 0x6f, 0x70, 0x73, 0x12, 0x3b,
	0x0a, 0x06, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x23,
	0x2e, 0x43, 0x61, 0x72, 0x53, 0x74, 0x61, 0x74, 0x65, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f,
	0x6c, 0x2e, 0x43, 0x61, 0x72, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x2e, 0x41, 0x63, 0x74,
	0x69, 0x6f, 0x6e, 0x52, 0x06, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x14, 0x0a, 0x05, 0x72,
	0x6f, 0x75, 0x74, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x72, 0x6f, 0x75, 0x74,
	0x65, 0x12, 0x3f, 0x0a, 0x0d, 0x72, 0x6f, 0x75, 0x74, 0x65, 0x53, 0x74, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x73, 0x18, 0x04, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x43, 0x61, 0x72, 0x53, 0x74,
	0x61, 0x74, 0x65, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2e, 0x53, 0x74, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x52, 0x0d, 0x72, 0x6f, 0x75, 0x74, 0x65, 0x53, 0x74, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x73, 0x22, 0x2c, 0x0a, 0x06, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x0d, 0x0a, 0x09,
	0x4e, 0x4f, 0x5f, 0x41, 0x43, 0x54, 0x49, 0x4f, 0x4e, 0x10, 0x00, 0x12, 0x08, 0x0a, 0x04, 0x53,
	0x54, 0x4f, 0x50, 0x10, 0x01, 0x12, 0x09, 0x0a, 0x05, 0x53, 0x54, 0x41, 0x52, 0x54, 0x10, 0x02,
	0x22, 0x16, 0x0a, 0x04, 0x53, 0x74, 0x6f, 0x70, 0x12, 0x0e, 0x0a, 0x02, 0x74, 0x6f, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x74, 0x6f, 0x22, 0xbf, 0x01, 0x0a, 0x07, 0x53, 0x74, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x3e, 0x0a, 0x08, 0x70, 0x6f, 0x73, 0x69,
	0x74, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x22, 0x2e, 0x43, 0x61, 0x72,
	0x53, 0x74, 0x61, 0x74, 0x65, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2e, 0x53, 0x74,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x50, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x08,
	0x70, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x1a, 0x60, 0x0a, 0x08, 0x50, 0x6f, 0x73, 0x69,
	0x74, 0x69, 0x6f, 0x6e, 0x12, 0x1a, 0x0a, 0x08, 0x6c, 0x61, 0x74, 0x69, 0x74, 0x75, 0x64, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x01, 0x52, 0x08, 0x6c, 0x61, 0x74, 0x69, 0x74, 0x75, 0x64, 0x65,
	0x12, 0x1c, 0x0a, 0x09, 0x6c, 0x6f, 0x6e, 0x67, 0x69, 0x74, 0x75, 0x64, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x01, 0x52, 0x09, 0x6c, 0x6f, 0x6e, 0x67, 0x69, 0x74, 0x75, 0x64, 0x65, 0x12, 0x1a,
	0x0a, 0x08, 0x61, 0x6c, 0x74, 0x69, 0x74, 0x75, 0x64, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x01,
	0x52, 0x08, 0x61, 0x6c, 0x74, 0x69, 0x74, 0x75, 0x64, 0x65, 0x42, 0x3e, 0x5a, 0x21, 0x2e, 0x2e,
	0x2f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x62, 0x61,
	0x5f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x3b, 0x62, 0x61, 0x5f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0xaa,
	0x02, 0x18, 0x47, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75,
	0x66, 0x2e, 0x62, 0x61, 0x5f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_CarStateProtocol_proto_rawDescOnce sync.Once
	file_CarStateProtocol_proto_rawDescData = file_CarStateProtocol_proto_rawDesc
)

func file_CarStateProtocol_proto_rawDescGZIP() []byte {
	file_CarStateProtocol_proto_rawDescOnce.Do(func() {
		file_CarStateProtocol_proto_rawDescData = protoimpl.X.CompressGZIP(file_CarStateProtocol_proto_rawDescData)
	})
	return file_CarStateProtocol_proto_rawDescData
}

var file_CarStateProtocol_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_CarStateProtocol_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_CarStateProtocol_proto_goTypes = []interface{}{
	(CarStatus_State)(0),        // 0: CarStateProtocol.CarStatus.State
	(CarCommand_Action)(0),      // 1: CarStateProtocol.CarCommand.Action
	(*CarStatus)(nil),           // 2: CarStateProtocol.CarStatus
	(*CarCommand)(nil),          // 3: CarStateProtocol.CarCommand
	(*Stop)(nil),                // 4: CarStateProtocol.Stop
	(*Station)(nil),             // 5: CarStateProtocol.Station
	(*CarStatus_Telemetry)(nil), // 6: CarStateProtocol.CarStatus.Telemetry
	(*CarStatus_Position)(nil),  // 7: CarStateProtocol.CarStatus.Position
	(*Station_Position)(nil),    // 8: CarStateProtocol.Station.Position
}
var file_CarStateProtocol_proto_depIdxs = []int32{
	6, // 0: CarStateProtocol.CarStatus.telemetry:type_name -> CarStateProtocol.CarStatus.Telemetry
	0, // 1: CarStateProtocol.CarStatus.state:type_name -> CarStateProtocol.CarStatus.State
	4, // 2: CarStateProtocol.CarStatus.stop:type_name -> CarStateProtocol.Stop
	4, // 3: CarStateProtocol.CarCommand.stops:type_name -> CarStateProtocol.Stop
	1, // 4: CarStateProtocol.CarCommand.action:type_name -> CarStateProtocol.CarCommand.Action
	5, // 5: CarStateProtocol.CarCommand.routeStations:type_name -> CarStateProtocol.Station
	8, // 6: CarStateProtocol.Station.position:type_name -> CarStateProtocol.Station.Position
	7, // 7: CarStateProtocol.CarStatus.Telemetry.position:type_name -> CarStateProtocol.CarStatus.Position
	8, // [8:8] is the sub-list for method output_type
	8, // [8:8] is the sub-list for method input_type
	8, // [8:8] is the sub-list for extension type_name
	8, // [8:8] is the sub-list for extension extendee
	0, // [0:8] is the sub-list for field type_name
}

func init() { file_CarStateProtocol_proto_init() }
func file_CarStateProtocol_proto_init() {
	if File_CarStateProtocol_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_CarStateProtocol_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CarStatus); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_CarStateProtocol_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CarCommand); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_CarStateProtocol_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Stop); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_CarStateProtocol_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Station); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_CarStateProtocol_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CarStatus_Telemetry); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_CarStateProtocol_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CarStatus_Position); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_CarStateProtocol_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Station_Position); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_CarStateProtocol_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_CarStateProtocol_proto_goTypes,
		DependencyIndexes: file_CarStateProtocol_proto_depIdxs,
		EnumInfos:         file_CarStateProtocol_proto_enumTypes,
		MessageInfos:      file_CarStateProtocol_proto_msgTypes,
	}.Build()
	File_CarStateProtocol_proto = out.File
	file_CarStateProtocol_proto_rawDesc = nil
	file_CarStateProtocol_proto_goTypes = nil
	file_CarStateProtocol_proto_depIdxs = nil
}
